name: swipeable_page_route
description: Swipe to navigate back and admire beautifully morphing widgets
version: 0.4.7
repository: https://github.com/JonasWanke/swipeable_page_route
screenshots:
  - description: Users can swipe to navigate back anywhere on the page and the app bar transitions beautifully
    path: doc/demo.gif

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  black_hole_flutter: ^1.1.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  list_diff: ^2.0.1

dev_dependencies:
